// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

namespace WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("UserId");

                    b.Property<float>("Value");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");

                    b.HasData(
                        new { Id = 1, Date = new DateTime(2019, 3, 4, 21, 24, 0, 290, DateTimeKind.Local), UserId = 1, Value = 70f },
                        new { Id = 2, Date = new DateTime(2019, 3, 3, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 71f },
                        new { Id = 3, Date = new DateTime(2019, 3, 2, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 72f },
                        new { Id = 4, Date = new DateTime(2019, 3, 1, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 73f },
                        new { Id = 5, Date = new DateTime(2019, 2, 28, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 74f },
                        new { Id = 6, Date = new DateTime(2019, 2, 27, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 75f },
                        new { Id = 7, Date = new DateTime(2019, 2, 26, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 76f },
                        new { Id = 8, Date = new DateTime(2019, 2, 25, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 77f },
                        new { Id = 9, Date = new DateTime(2019, 2, 24, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 78f },
                        new { Id = 10, Date = new DateTime(2019, 2, 23, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 79f },
                        new { Id = 11, Date = new DateTime(2019, 2, 22, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 80f },
                        new { Id = 12, Date = new DateTime(2019, 2, 21, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 81f },
                        new { Id = 13, Date = new DateTime(2019, 2, 20, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 82f },
                        new { Id = 14, Date = new DateTime(2019, 2, 19, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 83f },
                        new { Id = 15, Date = new DateTime(2019, 2, 18, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 84f },
                        new { Id = 16, Date = new DateTime(2019, 2, 17, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 85f },
                        new { Id = 17, Date = new DateTime(2019, 2, 16, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 86f },
                        new { Id = 18, Date = new DateTime(2019, 2, 15, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 87f },
                        new { Id = 19, Date = new DateTime(2019, 2, 14, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 88f },
                        new { Id = 20, Date = new DateTime(2019, 2, 13, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 89f },
                        new { Id = 21, Date = new DateTime(2019, 2, 12, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 70f },
                        new { Id = 22, Date = new DateTime(2019, 2, 11, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 71f },
                        new { Id = 23, Date = new DateTime(2019, 2, 10, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 72f },
                        new { Id = 24, Date = new DateTime(2019, 2, 9, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 73f },
                        new { Id = 25, Date = new DateTime(2019, 2, 8, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 74f },
                        new { Id = 26, Date = new DateTime(2019, 2, 7, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 75f },
                        new { Id = 27, Date = new DateTime(2019, 2, 6, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 76f },
                        new { Id = 28, Date = new DateTime(2019, 2, 5, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 77f },
                        new { Id = 29, Date = new DateTime(2019, 2, 4, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 78f },
                        new { Id = 30, Date = new DateTime(2019, 2, 3, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 79f },
                        new { Id = 31, Date = new DateTime(2019, 2, 2, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 80f },
                        new { Id = 32, Date = new DateTime(2019, 2, 1, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 81f },
                        new { Id = 33, Date = new DateTime(2019, 1, 31, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 82f },
                        new { Id = 34, Date = new DateTime(2019, 1, 30, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 83f },
                        new { Id = 35, Date = new DateTime(2019, 1, 29, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 84f },
                        new { Id = 36, Date = new DateTime(2019, 1, 28, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 85f },
                        new { Id = 37, Date = new DateTime(2019, 1, 27, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 86f },
                        new { Id = 38, Date = new DateTime(2019, 1, 26, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 87f },
                        new { Id = 39, Date = new DateTime(2019, 1, 25, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 88f },
                        new { Id = 40, Date = new DateTime(2019, 1, 24, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 89f },
                        new { Id = 41, Date = new DateTime(2019, 1, 23, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 70f },
                        new { Id = 42, Date = new DateTime(2019, 1, 22, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 71f },
                        new { Id = 43, Date = new DateTime(2019, 1, 21, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 72f },
                        new { Id = 44, Date = new DateTime(2019, 1, 20, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 73f },
                        new { Id = 45, Date = new DateTime(2019, 1, 19, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 74f },
                        new { Id = 46, Date = new DateTime(2019, 1, 18, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 75f },
                        new { Id = 47, Date = new DateTime(2019, 1, 17, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 76f },
                        new { Id = 48, Date = new DateTime(2019, 1, 16, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 77f },
                        new { Id = 49, Date = new DateTime(2019, 1, 15, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 78f },
                        new { Id = 50, Date = new DateTime(2019, 1, 14, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 79f },
                        new { Id = 51, Date = new DateTime(2019, 1, 13, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 80f },
                        new { Id = 52, Date = new DateTime(2019, 1, 12, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 81f },
                        new { Id = 53, Date = new DateTime(2019, 1, 11, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 82f },
                        new { Id = 54, Date = new DateTime(2019, 1, 10, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 83f },
                        new { Id = 55, Date = new DateTime(2019, 1, 9, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 84f },
                        new { Id = 56, Date = new DateTime(2019, 1, 8, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 85f },
                        new { Id = 57, Date = new DateTime(2019, 1, 7, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 86f },
                        new { Id = 58, Date = new DateTime(2019, 1, 6, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 87f },
                        new { Id = 59, Date = new DateTime(2019, 1, 5, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 88f },
                        new { Id = 60, Date = new DateTime(2019, 1, 4, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 89f },
                        new { Id = 61, Date = new DateTime(2019, 1, 3, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 70f },
                        new { Id = 62, Date = new DateTime(2019, 1, 2, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 71f },
                        new { Id = 63, Date = new DateTime(2019, 1, 1, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 72f },
                        new { Id = 64, Date = new DateTime(2018, 12, 31, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 73f },
                        new { Id = 65, Date = new DateTime(2018, 12, 30, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 74f },
                        new { Id = 66, Date = new DateTime(2018, 12, 29, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 75f },
                        new { Id = 67, Date = new DateTime(2018, 12, 28, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 76f },
                        new { Id = 68, Date = new DateTime(2018, 12, 27, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 77f },
                        new { Id = 69, Date = new DateTime(2018, 12, 26, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 78f },
                        new { Id = 70, Date = new DateTime(2018, 12, 25, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 79f },
                        new { Id = 71, Date = new DateTime(2018, 12, 24, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 80f },
                        new { Id = 72, Date = new DateTime(2018, 12, 23, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 81f },
                        new { Id = 73, Date = new DateTime(2018, 12, 22, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 82f },
                        new { Id = 74, Date = new DateTime(2018, 12, 21, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 83f },
                        new { Id = 75, Date = new DateTime(2018, 12, 20, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 84f },
                        new { Id = 76, Date = new DateTime(2018, 12, 19, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 85f },
                        new { Id = 77, Date = new DateTime(2018, 12, 18, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 86f },
                        new { Id = 78, Date = new DateTime(2018, 12, 17, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 87f },
                        new { Id = 79, Date = new DateTime(2018, 12, 16, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 88f },
                        new { Id = 80, Date = new DateTime(2018, 12, 15, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 89f },
                        new { Id = 81, Date = new DateTime(2018, 12, 14, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 70f },
                        new { Id = 82, Date = new DateTime(2018, 12, 13, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 71f },
                        new { Id = 83, Date = new DateTime(2018, 12, 12, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 72f },
                        new { Id = 84, Date = new DateTime(2018, 12, 11, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 73f },
                        new { Id = 85, Date = new DateTime(2018, 12, 10, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 74f },
                        new { Id = 86, Date = new DateTime(2018, 12, 9, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 75f },
                        new { Id = 87, Date = new DateTime(2018, 12, 8, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 76f },
                        new { Id = 88, Date = new DateTime(2018, 12, 7, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 77f },
                        new { Id = 89, Date = new DateTime(2018, 12, 6, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 78f },
                        new { Id = 90, Date = new DateTime(2018, 12, 5, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 79f },
                        new { Id = 91, Date = new DateTime(2018, 12, 4, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 80f },
                        new { Id = 92, Date = new DateTime(2018, 12, 3, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 81f },
                        new { Id = 93, Date = new DateTime(2018, 12, 2, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 82f },
                        new { Id = 94, Date = new DateTime(2018, 12, 1, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 83f },
                        new { Id = 95, Date = new DateTime(2018, 11, 30, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 84f },
                        new { Id = 96, Date = new DateTime(2018, 11, 29, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 85f },
                        new { Id = 97, Date = new DateTime(2018, 11, 28, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 86f },
                        new { Id = 98, Date = new DateTime(2018, 11, 27, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 87f },
                        new { Id = 99, Date = new DateTime(2018, 11, 26, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 88f },
                        new { Id = 100, Date = new DateTime(2018, 11, 25, 21, 24, 0, 293, DateTimeKind.Local), UserId = 1, Value = 89f }
                    );
                });

            modelBuilder.Entity("WebAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, FirstName = "Ferko", LastName = "Feric", PasswordHash = new byte[] { 55, 85, 245, 121, 163, 90, 53, 122, 45, 25, 230, 91, 10, 251, 6, 8, 247, 137, 62, 161, 60, 126, 125, 186, 125, 241, 96, 136, 231, 240, 28, 73, 203, 255, 60, 190, 12, 115, 138, 7, 127, 39, 42, 244, 93, 91, 205, 94, 219, 144, 5, 15, 12, 85, 52, 67, 88, 244, 119, 114, 68, 44, 75, 87 }, PasswordSalt = new byte[] { 149, 212, 200, 18, 63, 130, 252, 41, 212, 167, 214, 107, 235, 251, 159, 101, 55, 104, 196, 113, 7, 90, 218, 109, 70, 213, 200, 65, 107, 99, 120, 163, 2, 216, 75, 193, 166, 147, 89, 48, 99, 22, 235, 212, 177, 5, 58, 235, 48, 80, 56, 253, 149, 163, 110, 100, 73, 31, 40, 107, 49, 115, 197, 182, 73, 152, 142, 89, 244, 232, 89, 54, 219, 242, 184, 157, 26, 51, 56, 84, 229, 167, 254, 108, 84, 187, 29, 45, 56, 223, 75, 184, 202, 134, 39, 218, 96, 114, 50, 210, 70, 72, 16, 166, 122, 192, 118, 226, 199, 174, 215, 232, 136, 245, 3, 6, 134, 176, 85, 133, 90, 22, 33, 40, 93, 190, 36, 66 }, Username = "testUser" }
                    );
                });

            modelBuilder.Entity("WebAPI.Entities.Log", b =>
                {
                    b.HasOne("WebAPI.Entities.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
